name: 'publish docker image'

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: login to dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: get metadata for docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: amane/mediagoblin
        tags: |
          value=latest,event=push
          type=ref,event=tag
    - name: build and push docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
